version: '3'

services: 
    db: 
        image: mongo
        ports: 
            - 27017:27017
        restart: always
        environment: 
            # MONGO_INITDB_DATABASE: experienceapi
        volumes: 
            - ./mongodata:/data/db
    web:
        build: .
        ports: 
            - 8080:8080
        environment: 
            DATABASE_CONTAINER_NAME: "db"
        depends_on: 
            - db